# Generated by Django 2.1.7 on 2019-06-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tripinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data_de_partida', models.DateTimeField(verbose_name='data de partida')),
                ('destino', models.CharField(max_length=200)),
                ('data_de_chegada', models.DateTimeField(verbose_name='data de chegada')),
                ('motorista', models.CharField(max_length=200)),
            ],
        ),
    ]
